#!/bin/bash
# Interactive script to get token and add to Vercel

echo "🔐 Strapi Token Setup for Vercel"
echo "=================================="
echo ""
echo "✅ NEXT_PUBLIC_STRAPI_URL already added to Vercel!"
echo ""
echo "📝 To complete setup, you need to add STRAPI_API_TOKEN:"
echo ""
echo "1. Get your token:"
echo "   → Visit: https://bright-smile-1f47bc9d67.strapiapp.com/admin"
echo "   → Go to: Settings → API Tokens"
echo "   → Click: Create new API Token"
echo "   → Name: Frontend API Token"
echo "   → Type: Read-only (or Full-access)"
echo "   → Duration: Unlimited"
echo "   → Click Save and COPY THE TOKEN"
echo ""
echo "2. Then run this command:"
echo "   echo 'YOUR_TOKEN_HERE' | vercel env add STRAPI_API_TOKEN production"
echo "   echo 'YOUR_TOKEN_HERE' | vercel env add STRAPI_API_TOKEN preview"
echo "   echo 'YOUR_TOKEN_HERE' | vercel env add STRAPI_API_TOKEN development"
echo ""
echo "Or use the automated script:"
echo "   ./scripts/fix-vercel-strapi.sh YOUR_TOKEN_HERE"
echo ""
